// Catalogue de parfums (données indicatives : notes simplifiées, prix ≈ flacon standard en €).
// Ligne = [nom, maison, famille, notes, projection 1-5, tenue 1-5, poids 1(frais/léger)-5(dense/chaud), prix ≈ €]
(function (root) {
  const rows = [
    ['Acqua di Giò', 'Armani', 'aquatique', ['notes marines', 'bergamote', 'romarin', 'patchouli'], 3, 3, 1, 85],
    ['Bleu de Chanel EDP', 'Chanel', 'boisé', ['agrumes', 'encens', 'cèdre', 'santal', 'gingembre'], 3, 4, 3, 115],
    ['Sauvage EDT', 'Dior', 'aromatique', ['bergamote de Calabre', 'poivre', 'poivre du Sichuan', 'lavande', 'poivre rose', 'vétiver', 'patchouli', 'géranium', 'élémi', 'ambroxan', 'cèdre', 'labdanum'], 4, 4, 2, 105],
    ['Sauvage Elixir', 'Dior', 'épicé', ['cannelle', 'cardamome', 'lavande', 'réglisse', 'santal'], 5, 5, 5, 155],
    ['Aventus', 'Creed', 'boisé', ['ananas', 'bouleau', 'musc', 'mousse de chêne', 'bergamote'], 4, 4, 3, 380],
    ['Layton', 'Parfums de Marly', 'ambré', ['pomme', 'lavande', 'vanille', 'cardamome', 'santal'], 4, 5, 4, 250],
    ['Tobacco Vanille', 'Tom Ford', 'gourmand', ['feuille de tabac', 'épices', 'vanille', 'cacao', 'fève tonka', 'fleur de tabac', 'fruits secs', 'bois'], 4, 5, 5, 260],
    ['Terre d\'Hermès', 'Hermès', 'boisé', ['pamplemousse', 'orange', 'silex', 'poivre', 'poivre rose', 'cèdre de l\'Atlas', 'vétiver', 'benjoin'], 3, 4, 3, 90],
    ['Light Blue', 'Dolce & Gabbana', 'agrumes', ['citron', 'pomme', 'cèdre', 'musc'], 3, 3, 1, 85],
    ['Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'ambré', ['jasmin', 'safran', 'ambre gris', 'bois ambré', 'cèdre'], 5, 5, 4, 270],
    ['Santal 33', 'Le Labo', 'boisé', ['santal', 'cèdre', 'cuir', 'cardamome', 'iris', 'violette'], 3, 4, 3, 220],
    ['Another 13', 'Le Labo', 'musqué', ['ambroxan', 'musc', 'jasmin', 'mousse', 'citron'], 3, 5, 3, 220],
    ['Oud Wood', 'Tom Ford', 'oud', ['oud', 'bois de rose', 'cardamome', 'santal', 'vanille'], 3, 4, 4, 250],
    ['Black Opium', 'Yves Saint Laurent', 'gourmand', ['café', 'vanille', 'fleur d\'oranger', 'poire'], 4, 4, 4, 110],
    ['Libre', 'Yves Saint Laurent', 'floral', ['lavande', 'fleur d\'oranger', 'vanille', 'musc'], 4, 4, 3, 110],
    ['Y EDP', 'Yves Saint Laurent', 'aromatique', ['sauge', 'pomme', 'cèdre', 'fève tonka', 'genièvre'], 4, 4, 3, 105],
    ['La Nuit de l\'Homme', 'Yves Saint Laurent', 'épicé', ['cardamome', 'lavande', 'cèdre', 'vétiver'], 3, 3, 3, 95],
    ['Good Girl', 'Carolina Herrera', 'gourmand', ['tubéreuse', 'cacao', 'fève tonka', 'amande'], 4, 4, 4, 110],
    ['La Vie est Belle', 'Lancôme', 'gourmand', ['bergamote', 'poivre rose', 'framboise', 'rose de Damas', 'ylang-ylang', 'iris', 'patchouli', 'vanille', 'jasmin sambac', 'fleur d\'oranger', 'sucre filé'], 4, 4, 4, 105],
    ['Coco Mademoiselle', 'Chanel', 'floral', ['orange', 'rose', 'jasmin', 'patchouli', 'vétiver'], 4, 4, 3, 120],
    ['N°5 EDP', 'Chanel', 'floral', ['aldéhydes', 'ylang-ylang', 'rose', 'jasmin', 'vanille'], 3, 4, 3, 130],
    ['Chance Eau Tendre', 'Chanel', 'fruité', ['pamplemousse', 'coing', 'jasmin', 'musc'], 3, 3, 2, 120],
    ['Miss Dior EDP', 'Dior', 'floral', ['rose', 'muguet', 'pivoine', 'patchouli'], 3, 3, 2, 115],
    ['J\'adore', 'Dior', 'floral', ['ylang-ylang', 'rose de Damas', 'jasmin'], 3, 3, 2, 130],
    ['Oud Ispahan', 'Dior', 'oud', ['oud', 'rose', 'patchouli', 'santal'], 4, 5, 5, 250],
    ['Angel', 'Mugler', 'gourmand', ['patchouli', 'praliné', 'vanille', 'caramel', 'fruits rouges'], 5, 5, 5, 100],
    ['Alien', 'Mugler', 'floral', ['jasmin', 'cachemire', 'ambre blanc'], 4, 5, 3, 90],
    ['Flowerbomb', 'Viktor&Rolf', 'floral', ['freesia', 'orchidée', 'rose', 'patchouli', 'jasmin'], 4, 4, 4, 120],
    ['Spicebomb Extreme', 'Viktor&Rolf', 'épicé', ['cannelle', 'tabac', 'vanille', 'poivre'], 4, 4, 5, 95],
    ['Daisy', 'Marc Jacobs', 'fruité', ['fraise', 'violette', 'jasmin', 'musc blanc'], 3, 3, 2, 85],
    ['Si', 'Armani', 'floral', ['cassis', 'rose', 'vanille', 'patchouli'], 4, 4, 3, 100],
    ['Burberry Her', 'Burberry', 'fruité', ['mûre', 'framboise', 'jasmin', 'musc'], 4, 3, 3, 90],
    ['Eau Sauvage', 'Dior', 'agrumes', ['citron', 'basilic', 'hédione', 'vétiver', 'mousse de chêne'], 2, 3, 1, 100],
    ['Fahrenheit', 'Dior', 'cuir', ['violette', 'cuir', 'muscade', 'cèdre'], 4, 4, 4, 90],
    ['Jazz Club', 'Maison Margiela', 'ambré', ['poivre rose', 'citron', 'néroli', 'rhum', 'sauge sclarée', 'vétiver', 'styrax', 'tabac', 'vanille'], 3, 4, 4, 135],
    ['By the Fireplace', 'Maison Margiela', 'ambré', ['marron chaud', 'clou de girofle', 'vanille', 'fumée', 'gaïac'], 3, 4, 5, 150],
    ['Lazy Sunday Morning', 'Maison Margiela', 'musqué', ['muguet', 'poire', 'aldéhydes', 'ambrette', 'iris', 'rose', 'fleur d\'oranger', 'musc blanc', 'patchouli'], 2, 3, 1, 68],
    ['Invictus', 'Rabanne', 'aquatique', ['pamplemousse', 'notes marines', 'laurier', 'gaïac', 'ambre gris'], 4, 3, 2, 90],
    ['1 Million', 'Rabanne', 'épicé', ['pamplemousse', 'cannelle', 'cuir', 'ambre', 'menthe'], 5, 4, 4, 90],
    ['Stronger With You', 'Armani', 'gourmand', ['cardamome', 'châtaigne', 'vanille', 'sauge', 'poivre rose'], 3, 4, 4, 90],
    ['Le Male Elixir', 'Jean Paul Gaultier', 'gourmand', ['lavande', 'menthe', 'vanille', 'miel', 'fève tonka', 'benjoin'], 5, 5, 5, 115],
    ['Grey Vetiver', 'Tom Ford', 'boisé', ['pamplemousse', 'sauge', 'vétiver', 'poivre', 'muscade'], 3, 3, 2, 140],
    ['Tuscan Leather', 'Tom Ford', 'cuir', ['cuir', 'framboise', 'safran', 'thym', 'daim'], 4, 5, 5, 240],
    ['Ombré Leather', 'Tom Ford', 'cuir', ['cuir', 'cardamome', 'jasmin', 'ambre', 'patchouli'], 4, 5, 4, 190],
    ['Neroli Portofino', 'Tom Ford', 'agrumes', ['néroli', 'bergamote', 'mandarine', 'citron', 'ambre'], 3, 3, 1, 210],
    ['Encre Noire', 'Lalique', 'boisé', ['vétiver', 'cyprès', 'musc', 'cèdre'], 3, 3, 3, 35],
    ['Molecule 01', 'Escentric Molecules', 'musqué', ['iso e super'], 3, 4, 2, 110],
    ['Lime Basil & Mandarin', 'Jo Malone', 'agrumes', ['citron vert', 'basilic', 'mandarine', 'vétiver', 'ambre'], 2, 2, 1, 115],
    ['Wood Sage & Sea Salt', 'Jo Malone', 'aquatique', ['sauge', 'sel marin', 'ambrette', 'algue'], 2, 2, 1, 115],
    ['Green Irish Tweed', 'Creed', 'vert', ['citron', 'verveine', 'iris', 'violette', 'santal'], 3, 4, 2, 330],
    ['Vétiver', 'Guerlain', 'vert', ['vétiver', 'citron vert', 'pamplemousse', 'tabac'], 3, 3, 2, 90],
    ['Explorer', 'Montblanc', 'boisé', ['bergamote', 'poivre rose', 'vétiver', 'patchouli', 'cuir', 'cèdre'], 4, 4, 3, 60],
    ['Legend', 'Montblanc', 'aromatique', ['bergamote', 'lavande', 'ananas', 'fève tonka', 'mousse de chêne'], 3, 3, 2, 55],
    ['L\'Homme', 'Prada', 'musqué', ['iris', 'néroli', 'ambre', 'patchouli'], 2, 3, 2, 95],
    ['Gypsy Water', 'Byredo', 'boisé', ['bergamote', 'citron', 'genièvre', 'encens', 'pin', 'vanille', 'santal'], 3, 3, 3, 165],
    ['Portrait of a Lady', 'Frédéric Malle', 'floral', ['cassis', 'framboise', 'clou de girofle', 'rose de Turquie', 'cannelle', 'patchouli', 'santal', 'encens', 'benjoin', 'ambroxan', 'musc blanc'], 5, 5, 5, 235],
    ['Black Afgano', 'Nasomatto', 'oud', ['café', 'tabac', 'oud', 'encens', 'résine', 'cannabis'], 5, 5, 5, 130],
    ['Club de Nuit Intense Man', 'Armaf', 'boisé', ['citron', 'ananas', 'bouleau', 'musc', 'ambre gris'], 4, 4, 3, 35],
    ['Khamrah', 'Lattafa', 'gourmand', ['cannelle', 'datte', 'praliné', 'vanille', 'fève tonka'], 4, 5, 5, 40],
    ['Yara', 'Lattafa', 'gourmand', ['orchidée', 'héliotrope', 'vanille', 'musc', 'fève tonka'], 3, 4, 3, 30],
    ['Hawas', 'Rasasi', 'aquatique', ['pomme', 'cannelle', 'bergamote', 'ambre gris', 'muscade'], 4, 4, 2, 40],
    ['Voyage', 'Nautica', 'aquatique', ['pomme', 'feuille de lotus', 'notes marines', 'mousse', 'bois'], 2, 2, 1, 30],
    ['Mojave Ghost', 'Byredo', 'floral', ['ambrette', 'magnolia', 'santal', 'cèdre', 'musc'], 3, 3, 2, 195],
    ['Philosykos', 'Diptyque', 'vert', ['feuille de figuier', 'figue', 'noix de coco', 'cèdre'], 2, 3, 2, 150],
    ['Tam Dao', 'Diptyque', 'boisé', ['santal', 'cèdre', 'cyprès', 'ambre', 'poivre'], 2, 3, 3, 150],
    ['Do Son', 'Diptyque', 'floral', ['tubéreuse', 'fleur d\'oranger', 'iris', 'gingembre', 'musc'], 3, 3, 2, 150],
    ['Ambre Sultan', 'Serge Lutens', 'ambré', ['ambre', 'myrrhe', 'coriandre', 'benjoin', 'vanille'], 4, 5, 5, 140],
    ['Fille en Aiguilles', 'Serge Lutens', 'boisé', ['pin', 'encens', 'miel', 'ciste'], 4, 4, 4, 130],
    ['Vétiver Extraordinaire', 'Frédéric Malle', 'boisé', ['bergamote', 'orange amère', 'poivre rose', 'clou de girofle', 'vétiver', 'santal', 'cèdre', 'mousse de chêne', 'myrrhe', 'musc'], 3, 5, 3, 225],
    ['Musc Ravageur', 'Frédéric Malle', 'ambré', ['bergamote', 'mandarine', 'lavande', 'ambre', 'vanille', 'musc', 'santal'], 4, 5, 4, 260],
    ['Delina', 'Parfums de Marly', 'floral', ['rose', 'litchi', 'rhubarbe', 'musc', 'vanille'], 4, 4, 3, 290],
    ['Naxos', 'Xerjoff', 'gourmand', ['bergamote', 'citron', 'lavande', 'jasmin sambac', 'cannelle', 'miel', 'cachemire', 'tabac', 'fève tonka', 'vanille'], 4, 5, 4, 230],
    ['Side Effect', 'Initio', 'gourmand', ['rhum', 'tabac', 'vanille', 'cannelle', 'musc'], 4, 5, 5, 260],
    ['Reflection Man', 'Amouage', 'boisé', ['romarin', 'néroli', 'jasmin', 'iris', 'santal', 'cèdre'], 3, 4, 3, 290],
    ['Interlude Man', 'Amouage', 'épicé', ['poivre', 'encens', 'oud', 'ambre', 'patchouli'], 5, 5, 5, 300],
    ['Aqua Universalis', 'Maison Francis Kurkdjian', 'agrumes', ['citron', 'bergamote', 'fleur d\'oranger', 'musc'], 3, 3, 1, 190],
    ['Bergamote 22', 'Le Labo', 'agrumes', ['bergamote', 'pamplemousse', 'petit grain', 'musc', 'ambre'], 3, 3, 1, 220],
    ['Rose 31', 'Le Labo', 'épicé', ['rose', 'cumin', 'poivre', 'cèdre', 'vétiver', 'ambre'], 3, 4, 4, 220],
    ['Thé Noir 29', 'Le Labo', 'boisé', ['bergamote', 'figue', 'feuille de laurier', 'thé noir', 'épices', 'cèdre', 'vétiver', 'musc'], 3, 4, 3, 290],
    ['Oud Satin Mood', 'Maison Francis Kurkdjian', 'oud', ['oud', 'rose', 'violette', 'vanille', 'benjoin'], 5, 5, 5, 300],
    ['Bois Impérial', 'Essential Parfums', 'boisé', ['basilic thaï', 'poivre Timut', 'vétiver d\'Haïti', 'Georgywood', 'Akigalawood'], 4, 4, 3, 85],
    ['Myrrh & Tonka', 'Jo Malone', 'ambré', ['lavande', 'myrrhe', 'fève tonka', 'vanille'], 3, 4, 4, 165],
    ['Sydney', 'Contes de Parfums', 'aquatique', ['bergamote', 'ananas', 'anis', 'accord marin', 'jasmin', 'rose', 'poivre rose', 'muscade', 'cèdre', 'amberwood', 'mousse de chêne', 'musc'], 3, 3, 2, 0],
    ['724', 'Maison Francis Kurkdjian', 'musqué', ['bergamote', 'aldéhydes', 'pois de senteur', 'jasmin d\'Égypte', 'seringat', 'musc blanc', 'santal'], 3, 4, 2, 170],
    ['The Musc', 'Essential Parfums', 'musqué', ['gingembre rouge', 'lavandin', 'cire d\'abeille', 'santal', 'musc blanc'], 3, 4, 3, 82],
    ['Ella K', 'Ella K Parfums', 'ambré', [], 3, 4, 3, 0],
    ['Bianco Latte', 'Giardini di Toscana', 'gourmand', ['caramel', 'miel', 'coumarine', 'vanille', 'musc blanc'], 3, 4, 3, 125],
    ['Fleur Narcotique', 'Ex Nihilo', 'floral', ['bergamote', 'litchi', 'osmanthus', 'jasmin', 'freesia', 'pivoine', 'fleur d\'oranger', 'santal', 'mousse', 'musc'], 4, 5, 3, 420],
    ['Gris Charnel Extrait', 'BDK Parfums', 'boisé', ['cardamome', 'thé noir', 'figue', 'iris', 'ciste', 'vétiver', 'patchouli', 'vanille', 'santal', 'cèdre', 'fève tonka'], 4, 5, 4, 270],
    ['Orphéon', 'Diptyque', 'boisé', ['genièvre', 'jasmin', 'cèdre', 'fève tonka', 'tabac'], 3, 4, 3, 205],
    ['Mojave Ghost Absolu', 'Byredo', 'floral', ['ambrette', 'baie de nesberry', 'magnolia', 'santal', 'violette', 'ambre', 'cèdre', 'musc'], 3, 5, 3, 295],
    ['Buongiorno Dolce Far Niente', 'Acqua di Parma', 'agrumes', ['citron de Sicile', 'petit grain', 'bois de figuier', 'hédione', 'musc', 'cèdre de Virginie'], 2, 3, 1, 290],
    ['Straight to Heaven', 'Kilian', 'gourmand', ['rhum', 'muscade', 'vanille', 'fruits secs', 'patchouli', 'cèdre'], 4, 5, 5, 375],
    ['Nasaj', 'Oman Luxury', 'floral', ['mandarine', 'pamplemousse', 'poivre rose', 'cardamome', 'poire', 'tubéreuse', 'jasmin', 'néroli', 'lys', 'magnolia', 'gardénia', 'benjoin', 'santal', 'oliban', 'fève tonka', 'patchouli', 'ambroxan'], 4, 5, 4, 235],
    ['Néroli Hasbaya', 'Atelier Materi', 'floral', ['néroli', 'fleur d\'oranger', 'amande amère', 'pistache', 'rose de Damas', 'musc', 'baume du Pérou', 'santal blanc'], 3, 5, 3, 254],
    ['Guidance 46', 'Amouage', 'floral', ['eau de rose', 'poire', 'noisette', 'amande amère', 'oliban', 'poivre rose', 'rose', 'osmanthus', 'safran', 'jasmin sambac', 'santal', 'Akigalawood', 'vanille', 'ambrette', 'Georgywood', 'ambre gris', 'labdanum', 'cypriol'], 5, 5, 4, 490],
    ['Tuxedo', 'Yves Saint Laurent', 'boisé', ['feuille de violette', 'bergamote', 'coriandre', 'rose', 'muguet', 'poivre noir', 'ambre gris', 'patchouli', 'vanille Bourbon'], 4, 5, 4, 300],
    ['Ambre Russe', 'Parfum d\'Empire', 'ambré', ['vodka', 'champagne', 'thé noir fumé', 'coriandre', 'cannelle', 'ambre gris', 'vanille', 'labdanum', 'cuir de Russie'], 4, 5, 5, 130],
    ['Tam Dao Eau de Parfum', 'Diptyque', 'boisé', ['cyprès d\'Italie', 'ambre gris', 'santal', 'cèdre', 'ambre', 'bois de rose', 'musc blanc'], 3, 4, 3, 190],
    ['Fève Nectar', 'Place de la Rêverie', 'gourmand', ['bergamote', 'fleur d\'oranger', 'vanille', 'cacao', 'chocolat', 'fève tonka', 'benjoin', 'ambrette', 'musc'], 3, 5, 4, 245],
    ['Jasmin Rouge', 'Tom Ford', 'floral', ['poivre noir', 'poivre blanc', 'sauge sclarée', 'jasmin sambac', 'ylang-ylang', 'labdanum', 'ambre'], 4, 4, 4, 240],
    ['Stellar Times', 'Louis Vuitton', 'ambré', ['ambre', 'fleur d\'oranger', 'baume du Pérou'], 4, 5, 4, 0],
    ['Radical Rose', 'Matière Première', 'floral', ['safran', 'poivre rose', 'bergamote', 'rose centifolia', 'rose de Turquie', 'patchouli', 'labdanum', 'santal'], 4, 4, 3, 0],
    ['Rouge Trafalgar', 'Dior', 'fruité', ['framboise', 'feuille de cassis', 'patchouli', 'musc'], 4, 5, 4, 0],
    ['L\'Eau Pâle', 'Courrèges', 'aromatique', ['citron', 'poivre rose', 'petit grain', 'lavande', 'vétiver', 'iris'], 3, 3, 1, 110],
    ['Imagination', 'Louis Vuitton', 'agrumes', ['bergamote', 'orange de Sicile', 'cédrat', 'néroli', 'gingembre', 'cannelle', 'ambroxan', 'thé noir', 'bois de gaïac', 'oliban'], 4, 4, 2, 345],
    ['Néroli Amara', 'Van Cleef & Arpels', 'agrumes', ['citron d\'Italie', 'mandarine', 'bergamote', 'poivre rose', 'cyprès', 'fleur d\'oranger'], 2, 3, 1, 200],
    ['Ombre Nomade', 'Louis Vuitton', 'oud', ['oud', 'benjoin', 'oliban', 'framboise'], 5, 5, 5, 0],
    ['Acne Studios', 'Frédéric Malle', 'floral', ['aldéhydes', 'rose', 'violette', 'fleur d\'oranger', 'pêche', 'vanille', 'santal', 'encens', 'musc'], 4, 5, 3, 300],
    ['Purpose', 'Amouage', 'boisé', ['piment de la Jamaïque', 'bergamote', 'oliban', 'poivre rose', 'papyrus', 'rose', 'santal', 'vétiver', 'Akigalawood', 'safran', 'daim'], 4, 5, 4, 365],
    ['Ambert Sunset', 'Librery', 'ambré', ['abricot', 'safran', 'osmanthus', 'rose', 'iris pallida', 'jasmin', 'cuir', 'ambre', 'santal'], 4, 5, 4, 170],
    ['Ambre Papier', 'Atelier Materi', 'ambré', ['poivre noir', 'piment de la Jamaïque', 'mandarine rouge', 'jasmin', 'myrrhe', 'maté', 'safran', 'benjoin de Siam', 'vétiver d\'Haïti', 'fève tonka'], 3, 5, 4, 254],
    ['Ganymede', 'Marc-Antoine Barrois', 'cuir', ['mandarine d\'Italie', 'safran', 'violette', 'osmanthus', 'Akigalawood', 'immortelle', 'accord daim'], 4, 5, 3, 200],
    ['De Los Santos', 'Byredo', 'boisé', ['sauge sclarée', 'mirabelle', 'iris', 'ciste', 'musc', 'ambroxan', 'palo santo'], 3, 4, 2, 165],
    ['Étoile Filante', 'Louis Vuitton', 'floral', ['osmanthus', 'magnolia', 'abricot', 'cassis', 'jasmin'], 3, 4, 2, 230],
    ['Boss Bottled', 'Hugo Boss', 'boisé', ['pomme', 'géranium', 'cannelle', 'clou de girofle', 'santal', 'vétiver', 'cèdre', 'bois d\'olivier', 'ambre', 'musc'], 3, 3, 3, 60],
    ['Bleu de Chanel EDT', 'Chanel', 'boisé', ['citron', 'pamplemousse', 'poivre rose', 'menthe', 'gingembre', 'muscade', 'jasmin', 'encens', 'vétiver', 'cèdre', 'santal', 'labdanum'], 3, 3, 2, 115],
    ['Pour un Homme de Caron', 'Caron', 'aromatique', ['lavande', 'lavandin', 'rose de Turquie', 'vanille', 'ambre', 'musc'], 3, 4, 3, 80],
    ['Flacon ailé', '', 'ambré', [], 3, 4, 3, 0],
    ['Aqua Allegoria Rosa Verde', 'Guerlain', 'vert', ['concombre', 'bergamote', 'menthe', 'rose', 'accord poire', 'feuille de violette', 'iris', 'musc', 'cyprès'], 2, 2, 1, 145],
    ['Scandal By Night', 'Jean Paul Gaultier', 'gourmand', ['miel', 'tubéreuse', 'santal', 'fève tonka', 'vanille'], 4, 5, 4, 110],
    ['Paradoxe Intense', 'Prada', 'floral', ['poire', 'néroli', 'bergamote', 'mousse', 'jasmin', 'Ambrofix', 'Serenolide', 'ambre', 'vanille Bourbon'], 4, 4, 3, 115],
    ['Miss Dior Essence', 'Dior', 'floral', ['accord confiture de mûre', 'fleur de sureau', 'jasmin', 'accord chêne'], 4, 5, 3, 115],
    ['Shalimar', 'Guerlain', 'ambré', ['citron', 'bergamote', 'mandarine', 'cèdre', 'iris', 'patchouli', 'vétiver', 'jasmin', 'rose', 'vanille', 'encens', 'cuir', 'opoponax', 'civette', 'santal', 'fève tonka', 'musc'], 4, 5, 4, 95],
    ['Dior Homme Intense', 'Dior', 'boisé', ['lavande', 'iris', 'ambrette', 'poire', 'cèdre de Virginie', 'vétiver'], 3, 4, 3, 130],
    ['Stronger With You Intensely', 'Emporio Armani', 'gourmand', ['poivre rose', 'marron glacé', 'vanille', 'accord daim', 'vétiver', 'notes ambrées boisées'], 4, 5, 4, 85],
    ['Pure Musc Blanc', 'Narciso Rodriguez', 'musqué', ['jasmin', 'accord propre', 'musc', 'cèdre', 'vanille'], 3, 4, 1, 70],
    ['Libre Le Parfum', 'Yves Saint Laurent', 'floral', ['bergamote', 'mandarine', 'gingembre', 'safran', 'fleur d\'oranger', 'lavande', 'lavandin', 'vanille Bourbon', 'miel', 'vétiver'], 4, 5, 4, 140],
    ['Le Male', 'Jean Paul Gaultier', 'aromatique', ['menthe', 'armoise', 'cardamome', 'bergamote', 'lavande', 'fleur d\'oranger', 'cannelle', 'cumin', 'santal', 'vanille', 'cèdre', 'fève tonka', 'ambre'], 4, 4, 3, 95],
    ['L\'Interdit Rouge', 'Givenchy', 'floral', ['orange sanguine', 'accord rouge épicé', 'fleur d\'oranger', 'jasmin sambac', 'patchouli', 'santal'], 4, 4, 3, 95],
    ['Power of You', 'Emporio Armani', 'gourmand', ['fruit de la passion', 'accord frangipanier', 'vanille'], 3, 4, 3, 90],
  ];

  const CATALOG = rows.map(([name, house, family, notes, projection, longevity, weight, price]) => ({
    name, house, family, notes, projection, longevity, weight, price,
  }));


  // Collection de démonstration : 30 flacons qui couvrent chaleur, froid, pro, date, événement, famille, pluie, sport...
  // [nom, note /5, occasions favorisées]
  const OWNED = [
    ['Buongiorno Dolce Far Niente', 4, ['perso', 'amis']], ['Néroli Amara', 4, ['pro', 'famille']], ['L\'Eau Pâle', 4, ['pro', 'perso']],
    ['Sydney', 4, ['amis', 'perso']], ['Imagination', 5, ['pro', 'amis', 'date']], ['Sauvage EDT', 4, ['amis', 'event']],
    ['Lazy Sunday Morning', 3, ['famille', 'perso']], ['De Los Santos', 4, ['perso', 'pro']], ['Bleu de Chanel EDT', 4, ['pro', 'amis']],
    ['Bois Impérial', 5, ['pro', 'perso']], ['Vétiver Extraordinaire', 5, ['pro']], ['Terre d\'Hermès', 4, ['pro', 'amis', 'perso']],
    ['The Musc', 3, ['perso', 'famille']], ['Mojave Ghost Absolu', 4, ['pro', 'date']], ['Dior Homme Intense', 4, ['pro', 'date']],
    ['Jazz Club', 5, ['date', 'amis']], ['Naxos', 5, ['date', 'event']], ['Musc Ravageur', 4, ['date']],
    ['Bianco Latte', 4, ['famille', 'date', 'perso']], ['Libre Le Parfum', 4, ['date', 'event']], ['Myrrh & Tonka', 4, ['date', 'perso']],
    ['Baccarat Rouge 540', 5, ['event', 'date']], ['Black Afgano', 3, ['event']], ['Tuxedo', 4, ['event', 'pro']],
    ['Guidance 46', 4, ['event']], ['Fleur Narcotique', 4, ['event', 'date']],
    ['Tobacco Vanille', 5, ['date', 'event', 'perso']], ['Ambre Papier', 4, ['perso', 'date']], ['Thé Noir 29', 5, ['pro', 'perso']], ['Orphéon', 4, ['perso', 'amis']],
  ];
  const WISH = ['Tam Dao Eau de Parfum', '724', 'Ambert Sunset', 'Straight to Heaven', 'Gris Charnel Extrait', 'Ombre Nomade', 'Stellar Times', 'Radical Rose', 'Rouge Trafalgar', 'Néroli Hasbaya', 'Nasaj', 'Acne Studios', 'Ganymede', 'Purpose', 'Portrait of a Lady', 'Jasmin Rouge', 'Étoile Filante', 'Paradoxe Intense', 'Miss Dior Essence', 'La Vie est Belle', 'Scandal By Night', 'Aqua Allegoria Rosa Verde', 'Shalimar', 'J\'adore', 'Stronger With You Intensely', 'Power of You', 'L\'Interdit Rouge', 'Le Male', 'Pour un Homme de Caron', 'Boss Bottled', 'Ambre Russe', 'Ella K', 'Fève Nectar', 'Pure Musc Blanc'];
  if (typeof module !== 'undefined') module.exports = { CATALOG, OWNED, WISH };
  else { root.CATALOG = CATALOG; root.OWNED = OWNED; root.WISH = WISH; }
})(typeof window !== 'undefined' ? window : globalThis);
