// Cartes « À découvrir » de l'onglet Conseils : histoire, matières, nez, parfums cultes, insolite, lieux, astuces.
// Faits courants et vérifiables, écrits à notre façon ; ton sobre, quelques images, jamais de cours. Une carte = un petit fait.
(function (root) {
  const CATS = { histoire: 'Histoire', matiere: 'Matière première', nez: 'Nez culte', culte: 'Parfum culte', classique: 'Classique', gem: 'À essayer', insolite: 'Insolite', lieu: 'Lieu', astuce: 'Astuce', science: 'Le saviez-vous' };
  const T = [
    // ---- Histoire
    ['histoire', 'Le mot « parfum »', 'Il vient du latin per fumum : « par la fumée ». Avant les flacons, on parfumait en brûlant résines et bois, pour les dieux d\'abord, pour les hommes ensuite.'],
    ['histoire', 'Le kyphi des Égyptiens', 'Résines, miel, vin et raisins secs : le kyphi se brûlait dans les temples au coucher du soleil. Une recette qui s\'est transmise pendant des siècles.'],
    ['histoire', 'Néron et ses plafonds', 'Selon Suétone, la salle à manger de la Maison d\'or de Néron avait des plafonds mobiles qui laissaient tomber des fleurs et des gouttes de parfum sur les invités.'],
    ['histoire', 'L\'eau de la reine de Hongrie', 'Au XIVe siècle, une eau de romarin dans de l\'alcool passe pour l\'un des premiers parfums alcoolisés d\'Europe. On l\'employait aussi comme remède.'],
    ['histoire', 'Cologne, 1709', 'Giovanni Maria Farina crée à Cologne une eau de citrus et d\'herbes qui lui rappelle, écrit-il, « un matin de printemps italien ». Nous l\'appelons l\'eau de Cologne.'],
    ['histoire', '4711, un numéro de maison', 'Le célèbre 4711 doit son nom au numéro attribué à la maison de la marque quand les troupes françaises numérotèrent les bâtiments de Cologne, à la fin du XVIIIe siècle.'],
    ['histoire', 'La cour parfumée', 'Sous Louis XV, à Versailles, on aurait changé de parfum chaque jour. La cour en a gardé le surnom de « cour parfumée ».'],
    ['histoire', 'Le parfumeur de Marie-Antoinette', 'Jean-Louis Fargeon, son parfumeur, composait pour elle des bouquets de fleurs et de pommades. Il a survécu à la Révolution et rouvert boutique.'],
    ['histoire', 'Grasse, ville de gantiers', 'Au XVIe siècle, Grasse tanne le cuir et fabrique des gants. Pour masquer l\'odeur des peaux, on les parfume : la ville devient parfumeuse, puis capitale du parfum.'],
    ['histoire', 'Jicky, 1889', 'Aimé Guerlain compose Jicky avec des molécules de synthèse mêlées aux matières naturelles. On le cite souvent comme le premier parfum moderne.'],
    ['histoire', 'Fougère Royale, 1882', 'Chez Houbigant, Paul Parquet utilise la coumarine de synthèse pour évoquer une fougère. Or la fougère ne sent rien : l\'accord est une invention, et il a lancé toute une famille.'],
    ['histoire', 'Chypre, 1917', 'François Coty baptise « Chypre » une construction de bergamote, de mousse de chêne et de labdanum. Le nom rend hommage à l\'île, la famille est restée.'],
    ['histoire', 'L\'Heure Bleue, 1912', 'Jacques Guerlain nomme son parfum d\'après ce moment du crépuscule où le jour s\'efface. Poudré, tendre, un peu mélancolique : un parfum à l\'ambiance.'],
    ['histoire', 'Mitsouko, 1919', 'Jacques Guerlain s\'inspire d\'un roman de Claude Farrère, La Bataille. La pêche et la mousse de chêne y forment un chypre resté une référence.'],
    ['histoire', 'Tabac Blond, 1919', 'Chez Caron, un parfum de cuir et de tabac pour les femmes qui fument après la guerre. Il fait un clin d\'œil à l\'émancipation des années folles.'],
    ['histoire', 'Chanel N°5, 1921', 'Ernest Beaux présente plusieurs essais à Gabrielle Chanel, qui choisit le cinquième. Les aldéhydes lui donnent cette lumière froide qui sent le linge repassé et le champagne.'],
    ['histoire', 'Shalimar, 1925', 'Jacques Guerlain pose de la vanille synthétique sur des bergamotes et des résines. Il imagine l\'amour de l\'empereur Shah Jahan : Shalimar est le premier grand « oriental ».'],
    ['histoire', 'Joy, 1930', 'Jean Patou lance Joy en pleine crise de 1929 et l\'annonce comme « le parfum le plus cher du monde ». Des milliers de fleurs de jasmin et de rose de mai par flacon.'],
    ['histoire', 'Femme, 1944', 'Edmond Roudnitska signe Femme pour Rochas : une prune et une pêche posées sur des mousses. Un jus d\'après-guerre, sensuel, qui a marqué un siècle.'],
    ['histoire', 'Bandit et Fracas', 'Germaine Cellier, l\'une des rares femmes nez de son époque, crée Bandit (1944) et Fracas (1948) pour Robert Piguet. Un cuir sec, une tubéreuse magistrale.'],
    ['histoire', 'L\'Air du Temps, 1948', 'Chez Nina Ricci, Lalique dessine le flacon aux deux colombes, et Francis Fabron compose un œillet épicé sur un bouquet de fleurs. Un parfum de paix après la guerre.'],
    ['histoire', 'Eau Sauvage, 1966', 'Edmond Roudnitska pose pour Dior de l\'hédione, une molécule au jasmin transparent. La fraîcheur masculine élégante vient d\'être inventée.'],
    ['histoire', 'Opium, 1977', 'Yves Saint Laurent crée la polémique avec un nom, un orient et une campagne. Le flacon-inro et les épices chaudes en font un parfum qu\'on n\'oublie pas.'],
    ['histoire', 'Angel, 1992', 'Le premier grand gourmand : un accord de barbe à papa et de patchouli, signé Olivier Cresp et Yves de Chirin pour Mugler. Le flacon-étoile est rechargeable.'],
    ['histoire', 'CK One, 1994', 'Un parfum pour tout le monde, d\'Alberto Morillas et Harry Frémont. L\'unisexe quitte les marges et devient un phénomène.'],
    ['histoire', 'Le Mâle, 1995', 'Chez Jean Paul Gaultier, Francis Kurkdjian a 25 ans quand il compose la lavande et la vanille de Le Mâle, dans un flacon en torse de marin.'],
    ['histoire', 'Le métier de « nez »', 'Le terme désigne un parfumeur-créateur, formé pendant des années à reconnaître et à doser des milliers de matières. Son outil : une mémoire et un carnet de formules.'],
    ['histoire', 'Parfum et mode', 'Poiret en 1911 lance sa maison de parfums Rosine, la première d\'un couturier. Depuis, chaque maison de mode a voulu sa fragrance, parfois plus célèbre que ses robes.'],
    ['histoire', 'L\'orgue à parfums', 'En 1857, Septimus Piesse classe les odeurs comme les notes d\'une gamme et les range sur un « orgue ». Nos notes de tête, de cœur et de fond viennent de là.'],
    ['histoire', 'Le parfum, avant d\'être unisexe', 'Longtemps, hommes et femmes se parfumaient des mêmes eaux, de cologne, de fleurs d\'oranger et de violette. La coupure « pour elle / pour lui » est surtout du XXe siècle.'],
    // ---- Matière première
    ['matiere', 'L\'iris, patient', 'On sèche les rhizomes d\'iris pendant au moins trois ans avant d\'en tirer le « beurre d\'iris ». C\'est l\'une des matières les plus chères, à l\'odeur poudrée et un peu de carotte.'],
    ['matiere', 'La rose de mai', 'À Grasse, on cueille la rose centifolia à l\'aube, en mai, quand l\'odeur est à son sommet. Il faut plusieurs tonnes de pétales pour un kilo d\'huile essentielle.'],
    ['matiere', 'Le jasmin à la main', 'Le jasmin se récolte tôt le matin, fleur par fleur. Il faut plusieurs centaines de kilos de fleurs pour obtenir un seul kilo d\'absolue.'],
    ['matiere', 'L\'oud, une blessure', 'Dans certains Aquilaria, un champignon provoque la formation d\'une résine sombre pour protéger l\'arbre. Cette résine, c\'est l\'oud : animal, fumé, presque médicinal.'],
    ['matiere', 'L\'ambre gris', 'Sécrétion digestive du cachalot rejetée en mer, elle vieillit au soleil et au sel avant d\'échouer sur une plage. Elle sent la peau salée, tiède, un peu marine. On la remplace aujourd\'hui par l\'ambroxan.'],
    ['matiere', 'Le musc, avant la synthèse', 'Autrefois tiré d\'une glande du chevrotain porte-musc, il est aujourd\'hui entièrement remplacé par des muscs de synthèse : plus doux, plus propres, plus éthiques.'],
    ['matiere', 'La vanille, une orchidée', 'Chaque fleur de vanille ne s\'ouvre qu\'un jour et se féconde à la main. Le geste a été mis au point à La Réunion en 1841 par Edmond Albius, un jeune garçon de douze ans.'],
    ['matiere', 'Le vétiver, des racines', 'On distille les racines d\'une herbe cultivée à Haïti, à Java ou à La Réunion. L\'odeur est terreuse, fumée, fraîche à la fois : la terre après la pluie.'],
    ['matiere', 'Le santal, rare', 'Le santal de Mysore, au lait crémeux et chaud, est devenu si rare que l\'Inde en encadre la coupe. On trouve aujourd\'hui du santal d\'Australie, plus sec, ou des reconstitutions.'],
    ['matiere', 'La bergamote de Calabre', 'Presque toute la bergamote de parfumerie pousse dans une bande côtière de Calabre. Le zeste donne cette fraîcheur lumineuse qu\'on retrouve dans l\'eau de Cologne.'],
    ['matiere', 'Le néroli', 'La fleur du bigaradier donne le néroli. Son nom vient d\'une princesse de Nerola, au XVIIe siècle, qui en parfumait ses gants et son bain.'],
    ['matiere', 'L\'encens, des larmes', 'On incise l\'écorce d\'un Boswellia et la résine perle en larmes qui durcissent. Brûlée, elle devient fumée blanche, citronnée, un peu mystique.'],
    ['matiere', 'Le patchouli, des feuilles', 'Ses feuilles sont séchées puis distillées. L\'odeur est terreuse, humide, chocolatée. Dans les années 1970 elle devient celle d\'une génération.'],
    ['matiere', 'La mousse de chêne', 'Un lichen aux notes de sous-bois. Sa réglementation a transformé de nombreux classiques chypres : relire un vieux flacon et un neuf, c\'est comparer deux époques.'],
    ['matiere', 'Le bouleau, le cuir de Russie', 'Le goudron de bouleau sent la fumée, le cuir et le feu de bois. Il donne leur âme aux « cuirs de Russie », comme le Cuir de Russie de Chanel, en 1924.'],
    ['matiere', 'La lavande de Provence', 'La vraie lavande pousse en altitude et sent plus fin que le lavandin, plus camphré et plus productif. Les deux se côtoient dans les eaux de toilette.'],
    ['matiere', 'La tubéreuse', 'Fleur blanche d\'origine mexicaine, enivrante, presque animale de près. Elle donne aux parfums une présence qui remplit la pièce.'],
    ['matiere', 'L\'ylang-ylang', 'Aux Comores, à Madagascar, on distille ses fleurs jaunes en plusieurs fractions. La première, dite « extra », est la plus florale et la plus fine.'],
    ['matiere', 'Le cèdre, du crayon', 'L\'odeur d\'un crayon taillé : sec, boisé, un peu fumé. Le cèdre est l\'une des bases boisées les plus utilisées en parfumerie, des plus discrètes aux plus lumineuses.'],
    ['matiere', 'L\'enfleurage', 'Avant la distillation moderne, on posait des pétales sur de la graisse qui captait l\'odeur. Un travail de patience, abandonné pour les solvants volatils.'],
    ['matiere', 'Concrète et absolue', 'On lave la fleur à un solvant et on obtient la concrète, cireuse. On la lave ensuite à l\'alcool : c\'est l\'absolue, plus pure, qui rentre dans les parfums.'],
    ['matiere', 'Le headspace', 'On enferme une fleur vivante sous une cloche pour capter l\'air autour d\'elle. Cette technique rend l\'odeur d\'une fleur qu\'on ne sait pas extraire, comme le muguet ou le lilas.'],
    ['matiere', 'Le muguet n\'a pas d\'huile', 'Impossible d\'extraire l\'odeur du muguet. Les parfumeurs la reconstituent de toutes pièces, comme dans Diorissimo de Roudnitska, en 1956.'],
    ['matiere', 'Le café en parfumerie', 'Un absolu de café torréfié donne aux parfums gourmands une facette amère, presque salée, qui évite le sucré trop sage.'],
    ['matiere', 'L\'aldéhyde', 'Une famille de molécules qui sentent la cire, le linge, le champagne. Le N°5 de Chanel en a fait sa signature.'],
    ['matiere', 'La molécule Iso E Super', 'Un boisé doux et velouté, presque invisible, qui donne du volume. Escentric Molecules l\'a mis en vedette en 2006 avec Molecule 01, composé de cette seule molécule.'],
    ['matiere', 'La calone', 'Découverte par un laboratoire en 1966, la calone a l\'odeur de l\'air marin. Elle a lancé la vague des parfums aquatiques dans les années 1990.'],
    ['matiere', 'L\'hédione', 'Une molécule de jasmin transparent, légère, presque lumineuse. Depuis Eau Sauvage, elle est devenue discrète et omniprésente.'],
    ['matiere', 'L\'ambroxan', 'Né en laboratoire, il évoque l\'ambre gris : sec, minéral, salé et chaud. Il donne leur sillage à de nombreux parfums modernes.'],
    ['matiere', 'Les résines, des baumes', 'Benjoin, labdanum, myrrhe, oliban : les résines apportent le côté ambré, chaud, vanillé. Elles fixent les autres notes et font durer le parfum.'],
    ['matiere', 'Le bois de gaïac', 'Un bois dense, fumé, qui a l\'odeur d\'un feu de camp en douceur. Il est souvent associé au cuir et au tabac.'],
    // ---- Nez culte
    ['nez', 'Jacques Guerlain', 'Petit-fils du fondateur de la maison, il signe L\'Heure Bleue, Mitsouko, Shalimar, Vol de Nuit. Son esprit se reconnaît à ce qu\'on appelle la « guerlinade », une signature poudrée et vanillée.'],
    ['nez', 'Ernest Beaux', 'Formé en Russie, il rapporte à Paris l\'idée d\'un parfum « de femme qui sent la femme » : le N°5, puis le Cuir de Russie, pour Chanel.'],
    ['nez', 'Edmond Roudnitska', 'Femme, Eau Sauvage, Diorissimo : trois parfums, trois révolutions. Il défendait la parfumerie comme un art à part entière, pas comme un produit de mode.'],
    ['nez', 'Germaine Cellier', 'Elle compose Vent Vert, Bandit et Fracas. Un galbanum vert et frais, un cuir sec, une tubéreuse sans retenue : l\'après-guerre a trouvé là son audace.'],
    ['nez', 'Annick Goutal', 'Pianiste avant d\'être parfumeuse, elle crée Eau d\'Hadrien, un citron italien lumineux, et fonde sa maison en 1981. Ses parfums se lisent comme des mélodies.'],
    ['nez', 'Sophia Grojsman', 'La « reine des roses », capable de donner du volume à une rose en quelques traits. On lui doit Paris pour Yves Saint Laurent et Trésor pour Lancôme.'],
    ['nez', 'Jean-Claude Ellena', 'Parfumeur de Hermès de 2004 à 2016, il a défendu un style épuré et transparent. Terre d\'Hermès et Un Jardin en Méditerranée sont ses aquarelles.'],
    ['nez', 'Francis Kurkdjian', 'Le Mâle, Narciso for Her, puis Baccarat Rouge 540 : une signature de transparence et de sucre filé. Il a fondé sa maison en 2009 et dirige la création de Dior depuis 2021.'],
    ['nez', 'Dominique Ropion', 'Il compose des rois du « blanc » : Carnal Flower, Portrait of a Lady. Tubéreuse, rose, encens : il sait faire tenir debout les matières les plus intenses.'],
    ['nez', 'Maurice Roucel', 'Musc Ravageur pour Frédéric Malle, Insolence pour Guerlain : des musques sensuels et épicés qui sont devenus des pièces de collection.'],
    ['nez', 'Alberto Morillas', 'CK One, Acqua di Giò : deux parfums qui ont changé la fraîcheur, et bien d\'autres depuis. Un maître de la lumière légère.'],
    ['nez', 'Pierre Bourdon', 'On lui doit Kouros, Cool Water et Iris Poudre : trois ambiances nettes, des parfums à idée qui ont tracé leur sillon.'],
    ['nez', 'Christopher Sheldrake', 'Complice de Serge Lutens, il compose depuis les années 1990 Ambre Sultan, Chergui ou Fille en Aiguilles : des résines chaudes, des épices, des forêts.'],
    ['nez', 'Jacques Polge', 'Nez de Chanel de 1978 à 2013, il a veillé sur le N°5 et créé Coco, Allure, Bleu de Chanel. Son fils Olivier lui a succédé.'],
    ['nez', 'Christine Nagel', 'Passée par Quest, Firmenich, Jo Malone, elle devient nez de Hermès en 2014, après Jean-Claude Ellena. Son style : l\'émotion, le toucher, la chaleur.'],
    ['nez', 'Mathilde Laurent', 'Formée chez Guerlain, elle a été nez de Cartier : La Panthère, Les Heures de Parfum. Des parfums d\'émotions précises.'],
    ['nez', 'Thierry Wasser', 'Il prend la parfumerie de Guerlain en 2008, après Jean-Paul Guerlain, et signe notamment Mon Guerlain.'],
    ['nez', 'Olivier Cresp', 'Co-auteur d\'Angel et auteur de Light Blue : le patchouli sucré et la pomme verte des années 1990 et 2000, c\'est lui.'],
    // ---- Parfum culte
    ['culte', 'Santal 33', 'Le Labo, New York, 2011 : un santal cuiré et sec, entre cèdre et violette, devenu un bruit de fond dans les rues de Brooklyn et d\'ailleurs. Un parfum qui divise : on l\'aime ou on le trouve partout.'],
    ['culte', 'Baccarat Rouge 540', 'Né en 2015 pour fêter les 250 ans de Baccarat, il doit son nom au rouge du cristal, où l\'on fond de l\'or à 540°C. Jasmin, safran, ambroxan, une trace de sucre filé.'],
    ['culte', 'Terre d\'Hermès, 2006', 'Jean-Claude Ellena y glisse de l\'orange et du silex. Un minéral chaud, qu\'on a comparé à une pierre au soleil : une idée de masculin loin des clichés.'],
    ['culte', 'Sauvage, 2015', 'François Demachy pour Dior : une bergamote de Calabre et une dose très généreuse d\'ambroxan. L\'un des parfums les plus vendus du monde.'],
    ['culte', 'Aventus, 2010', 'Creed raconte un parfum inspiré d\'un conquérant. Ananas, bouleau, musc : un parfum que les collectionneurs comparent lot après lot.'],
    ['culte', 'Black Orchid, 2006', 'Tom Ford y mêle truffe, orchidée et patchouli. Sombre, presque noir : le début des parfums « de caractère » en grande distribution de luxe.'],
    ['culte', 'Tobacco Vanille, 2007', 'Tom Ford, collection Private Blend : tabac blond, vanille, épices. L\'image d\'un club anglais où l\'on s\'attarde après le dîner.'],
    ['culte', 'Acqua di Giò, 1996', 'Alberto Morillas évoque la Méditerranée : citron vert, jasmin, notes marines. L\'une des fraîcheurs aquatiques les plus portées au monde.'],
    ['culte', 'Light Blue, 2001', 'Pomme verte, citron de Sicile, cèdre : Dolce & Gabbana capte un été entier, du bleu du ciel au blanc du linge.'],
    ['culte', 'Fahrenheit, 1988', 'Dior y met une note de violette qui évoque l\'essence, métallique, étrange. On l\'adore ou on la tolère : jamais on ne l\'oublie.'],
    ['culte', 'Shalimar', 'Un siècle après, la vanille fumée de Shalimar reste une référence. Ceux qui l\'ont sentie sur leur grand-mère la reconnaissent les yeux fermés.'],
    ['culte', 'Chanel N°19', 'Lancé en 1971, il porte le numéro du jour de naissance de Gabrielle Chanel, le 19 août. Un iris et un galbanum verts, secs, presque androgynes : un parfum d\'allure.'],
    ['culte', 'Poison, 1985', 'Une prune, une tubéreuse, un miel sombre dans un flacon en forme de pomme. Dior en fait un coup d\'éclat : un parfum qui précède celle qui le porte.'],
    ['culte', 'Black Afgano, Nasomatto', 'Du cannabis, de l\'oud, de la résine : un parfum de fumerie qui divise. Il a des fans fidèles dans les cercles de niche.'],
    ['culte', 'Narciso Rodriguez for Her', 'Un musc sensuel, signé Francis Kurkdjian et Christine Nagel, qui a donné un souffle de peau tiède au début des années 2000.'],
    ['culte', 'Molecule 01', 'Un seul ingrédient, l\'Iso E Super, sur la peau. Le parfum révèle autant l\'odeur de la personne qui le porte que la molécule elle-même.'],
    // ---- Classique
    ['classique', 'Vétiver de Guerlain, 1959', 'Jean-Paul Guerlain en fait un vétiver sec et vert, sans chichis. Une élégance rare, que l\'on retrouve dans les placards depuis soixante ans.'],
    ['classique', 'Habit Rouge, 1965', 'Un cuir, des épices, de la vanille : Jean-Paul Guerlain s\'inspire des cavaliers en veste rouge. Un classique qui donne le ton aux orientaux masculins.'],
    ['classique', 'Pour un Homme de Caron, 1934', 'Lavande, vanille : deux notes toutes simples, assemblées si bien que le parfum est resté presque inchangé depuis. L\'élégance du barbier.'],
    ['classique', 'Diorissimo, 1956', 'Christian Dior adorait le muguet. Roudnitska en fait un parfum frais, vert, floral : l\'idée même du printemps.'],
    ['classique', 'Eau d\'Hadrien', 'Un citron et un cyprès, sous un soleil d\'Italie. Un classique d\'été qui n\'a jamais pris une ride.'],
    ['classique', 'Kouros, 1981', 'Yves Saint Laurent, Pierre Bourdon : un fougère animal, épicé, un peu sauvage. Il porte le nom d\'une statue grecque.'],
    ['classique', 'Cool Water, 1988', 'Pierre Bourdon pour Davidoff invente l\'aquatique masculin : menthe, lavande, notes marines. Une vague qui a duré trente ans.'],
    ['classique', 'Vol de Nuit, 1933', 'Jacques Guerlain rend hommage à Saint-Exupéry et à l\'aviation de nuit. Un parfum d\'altitude, de résine et d\'orange amère.'],
    ['classique', 'Arpège, 1927', 'Jeanne Lanvin le crée pour sa fille. Un floral aldéhydé, élégant, que l\'on reconnaît dans le flacon boule noir et or.'],
    ['classique', 'Opium et Obsession', 'Dans les années 1980, les parfums deviennent narratifs : on ne porte plus seulement une odeur, on porte un scandale, un mythe, un personnage.'],
    // ---- À essayer (confidentiels, sans rien promettre)
    ['gem', 'Ambre Sultan', 'Serge Lutens, 1993 : un ambre dense, herbacé, résineux, loin des douceurs trop sucrées. À sentir en hiver.'],
    ['gem', 'Féminité du Bois', 'Serge Lutens, 1992 : un cèdre et des fruits secs, un bois miel et épices. Pour qui aime les boiseries chaudes.'],
    ['gem', 'Fille en Aiguilles', 'Une forêt de pins et d\'encens, signée Serge Lutens. À essayer quand on veut sentir l\'hiver sans neige.'],
    ['gem', 'Les parfums d\'ateliers', 'Atelier des Ors, Matière Première, Une Nuit Nomade : ces maisons à petits tirages travaillent une matière à la fois. Excellent terrain pour trouver sa signature.'],
    ['gem', 'Un Jardin en Méditerranée', 'Hermès, 2003, Jean-Claude Ellena : figuier, cyprès, une fraîcheur de feuilles. Pour qui rêve d\'un jardin sans y être.'],
    ['gem', 'Les parfums de cuir', 'Le cuir en parfumerie se compose de bouleau, de safran, de styrax. Il peut être sec, fruité, doux ou sombre : un territoire immense.'],
    ['gem', 'Les parfums de thé', 'Le thé vert, noir ou fumé donne des sillages calmes, un peu mats. Thé Noir 29 de Le Labo, ou un Hermès : ce sont des parfums pour l\'après-midi.'],
    ['gem', 'Les encens', 'Des encens sacrés aux encens boisés : ils posent un silence autour de soi. Beaucoup les choisissent pour se concentrer ou se recueillir.'],
    // ---- Insolite
    ['insolite', 'La mémoire d\'une odeur', 'L\'odorat est relié au système limbique, siège des émotions et de la mémoire. Une odeur peut ressusciter un souvenir plus vite qu\'une image : la madeleine de Proust.'],
    ['insolite', 'Le nez s\'habitue', 'Au bout d\'un moment, on ne sent plus son propre parfum. Ce n\'est pas qu\'il s\'est envolé : le cerveau l\'a classé comme du bruit de fond.'],
    ['insolite', 'Le grain de café', 'En boutique, on propose parfois des grains de café entre deux parfums. L\'effet réel est discuté : respirer l\'air frais ou le creux de son coude marche aussi bien.'],
    ['insolite', 'Le kōdō, la voie de l\'encens', 'Au Japon, on « écoute » l\'encens, comme on pratique la calligraphie ou la cérémonie du thé. On ne dit pas qu\'on sent, mais qu\'on écoute.'],
    ['insolite', 'Les attars de Kannauj', 'En Inde, la ville de Kannauj distille depuis des siècles des fleurs et des herbes dans des alambics de cuivre, avec de l\'huile de bois de santal. Ce sont les attars.'],
    ['insolite', 'Le bakhoor', 'Dans le Golfe, on parfume ses invités avec du bois d\'oud ou du bakhoor, des copeaux trempés d\'essences. Une façon de souhaiter la bienvenue.'],
    ['insolite', 'Le pays de l\'encens', 'Au Dhofar, au sud d\'Oman, les arbres à encens ont été inscrits au patrimoine mondial de l\'UNESCO. On y récolte une résine presque blanche, la plus fine.'],
    ['insolite', 'L\'Osmothèque', 'À Versailles, cette bibliothèque d\'odeurs conserve des milliers de parfums, dont des formules disparues. On y sent encore des parfums d\'avant les molécules de synthèse.'],
    ['insolite', 'Un nez à l\'école', 'Pour devenir nez, il faut des années : apprendre des centaines puis des milliers de matières, les identifier sans étiquette, les doser en gouttes.'],
    ['insolite', 'Parfum et peau', 'Le même jus ne sent pas pareil d\'une peau à l\'autre : sécheresse, chaleur, alimentation, tout joue. Une peau sèche fait tomber les notes plus vite.'],
    ['insolite', 'Un parfum, trois temps', 'La tête s\'évapore en quelques minutes, le cœur dure une à deux heures, le fond reste tout l\'après-midi, parfois sur le pull le lendemain.'],
    ['insolite', 'Concentrations', 'Environ 5 à 15 % de jus dans une eau de toilette, 15 à 20 % dans une eau de parfum, 20 à 30 % dans un extrait. Plus de jus ne veut pas dire plus fort : c\'est surtout plus de profondeur.'],
    ['insolite', 'Extrait, esprit, absolu', 'Ces versions ne sont pas des copies plus fortes : la plupart sont réécrites. Un extrait peut être plus sombre, plus résineux, plus doux que l\'eau de parfum dont il dérive.'],
    ['insolite', 'Pourquoi un parfum change', 'Les maisons reformulent leurs jus : une matière devient rare, interdite ou trop chère. Un flacon ancien et un flacon récent peuvent sentir très différemment.'],
    ['insolite', 'Parfum de cinéma', 'Nina Ricci, Chanel, Dior : les maisons de parfum ont souvent été des productrices de rêve. Marilyn Monroe aurait dit ne dormir qu\'avec quelques gouttes de N°5.'],
    ['insolite', 'Les noms de parfums', 'Un nom est parfois choisi avant le jus : « Opium » a fait scandale, « Poison » aussi, « Angel » a rassuré. Un titre raconte le parfum avant qu\'on le sente.'],
    ['insolite', 'Une pierre dans un flacon', 'Baccarat, Lalique, Saint-Louis : le flacon est un objet d\'art. Certains flacons Lalique, comme ceux de L\'Air du Temps, sont des pièces de collection.'],
    // ---- Lieu
    ['lieu', 'Grasse, la ville des essences', 'Entre mer et collines, Grasse cultive la rose, le jasmin, la tubéreuse. Le savoir-faire parfumé du Pays de Grasse figure au patrimoine immatériel de l\'UNESCO depuis 2018.'],
    ['lieu', 'La vallée des roses', 'En Bulgarie, autour de Kazanlak, on cultive la rose de Damas depuis des siècles. Chaque année, une fête célèbre la cueillette.'],
    ['lieu', 'Isparta, rose de Turquie', 'La région d\'Isparta produit une grande part de la rose de Damas du monde. Ses parfums sont plus épicés, plus fruités que ceux de Bulgarie.'],
    ['lieu', 'Kashan, l\'eau de rose', 'En Iran, on distille à Kashan et à Qamsar des roses en eau de rose, pour la cuisine, les mosquées, la fraîcheur du matin. Une tradition ancienne.'],
    ['lieu', 'La Calabre', 'Reggio Calabria, au pied de la botte italienne, donne presque toute la bergamote du monde. Les agrumes y parfument les rues en hiver.'],
    ['lieu', 'Haïti et le vétiver', 'L\'un des plus grands producteurs mondiaux de vétiver. Les racines sont arrachées à la main, séchées, puis distillées.'],
    ['lieu', 'Madagascar, vanille et ylang', 'Madagascar et ses îles voisines produisent l\'essentiel de la vanille. Nosy Be, la région d\'ylang-ylang, sent la fleur blanche sous la chaleur.'],
    ['lieu', 'Florence, Santa Maria Novella', 'Des moines dominicains y préparent des remèdes et des eaux depuis le XVIIe siècle. L\'une des plus anciennes pharmacies d\'Europe : l\'Acqua della Regina est d\'abord un cadeau à Catherine de Médicis.'],
    ['lieu', 'Cologne', 'La ville a donné son nom à l\'eau de Cologne. Aujourd\'hui encore, 4711 et Farina s\'y disputent l\'héritage.'],
    ['lieu', 'Paris, la place Vendôme', 'La rue de la Paix, la place Vendôme, la rue Saint-Honoré : les couturiers et joailliers y ont ouvert leurs salons de parfums. Aujourd\'hui encore, une adresse y fait un parfum.'],
    ['lieu', 'Mysore', 'Cette ville du sud de l\'Inde a donné son nom au meilleur santal. Le bois y est encadré par l\'État depuis des décennies.'],
    ['lieu', 'Le Maroc, fleurs d\'oranger', 'À Marrakech, l\'odeur des orangers en fleurs au printemps est un classique. Les eaux de fleur d\'oranger y servent à la cuisine comme à la toilette.'],
    ['lieu', 'Les Comores', 'L\'archipel est l\'un des principaux producteurs mondiaux d\'ylang-ylang. On y distille dans de grandes cuves, au pied des champs.'],
    ['lieu', 'Versailles et son jardin', 'Les orangers, les parterres de Le Nôtre, les musées : entre Osmothèque et Grand Trianon, Versailles est une vitrine de l\'histoire du parfum.'],
    // ---- Astuce
    ['astuce', 'Là où la peau est chaude', 'Poignets, creux du cou, pli du coude : la chaleur fait « monter » le parfum. Une goutte suffit, deux sur un jus puissant.'],
    ['astuce', 'Ne frotte pas', 'Frotter les poignets l\'un contre l\'autre écrase les notes de tête. Mieux vaut poser et laisser sécher : le parfum se déroule dans l\'ordre voulu par le nez.'],
    ['astuce', 'Teste sur la peau', 'La mouillette donne une idée, la peau donne la vérité. Attends une demi-heure puis quelques heures : le cœur et le fond se révèlent à leur rythme.'],
    ['astuce', 'Un à la fois', 'En boutique, trois parfums au maximum, un par bras, un sur mouillette. Au-delà, le nez sature et tout se ressemble.'],
    ['astuce', 'La peau sèche', 'Un peu de crème neutre avant le parfum aide à le faire durer. Les peaux sèches font fuir les notes vite ; les peaux grasses les retiennent.'],
    ['astuce', 'Vêtements', 'Un parfum tient plus longtemps sur un pull que sur la peau. Vaporise à distance, sur un tissu qui ne tache pas, et teste d\'abord sur une manche.'],
    ['astuce', 'Conserver ses flacons', 'La lumière, la chaleur et l\'humidité abîment un parfum. Évite la salle de bain : un tiroir ou son coffret conserve les jus plusieurs années.'],
    ['astuce', 'Le layering', 'Superposer deux parfums fonctionne mieux avec une base douce (vanille, musc, ambre) et une note plus claire par-dessus. Commence par deux sprays, pas plus.'],
    ['astuce', 'Une peau, une saison', 'L\'hiver aime les ambrés, les boisés, les gourmands. L\'été préfère les agrumes, les verts, les musqués clairs. La chaleur amplifie : on vaporise moins.'],
    ['astuce', 'Dans la zone', 'Pour se concentrer, beaucoup choisissent des encens, des bois secs, des thés : des parfums qui posent un silence autour de soi.'],
    ['astuce', 'Au bureau', 'Un parfum de bureau se sent à un bras de distance, pas dans le couloir. Choisis un jus propre, clair, avec une projection douce, et vaporise une fois.'],
    ['astuce', 'Les échantillons', 'Avant d\'acheter un flacon, vis quelques jours avec un échantillon : dans la rue, au bureau, un soir de pluie. Un parfum se juge dans la durée.'],
    ['astuce', 'Faire durer', 'Pose-le sur une peau hydratée, vaporise aussi les cheveux (à distance), et prends-en un fond plus résineux, plus vanillé : il tiendra plus longtemps.'],
    ['astuce', 'Offrir un parfum', 'Choisis un jus que tu connais, pas ce que tu aimerais sentir. Mieux : offre un coffret découverte, pour qu\'elle ou il puisse élire son préféré.'],
  ];
  root.TIPS = T.map((t, i) => ({ id: i, c: t[0], t: t[1], x: t[2] }));
  root.TIPS_CATS = CATS;
})(typeof window !== 'undefined' ? window : globalThis);
